minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
   - "@zayne-labs/*"

strictDepBuilds: false

packages:
   - apps/*
   - packages/*

allowBuilds:
   esbuild: set this to true or false
   sharp: set this to true or false
   unrs-resolver: set this to true or false
